logging:
  level:
    root: DEBUG

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/testetecnicowefin?allowPublicKeyRetrieval=true
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: person-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        temp:
          use_jdbc_metadata_defaults: false
  sql:
    init:
      mode: never

datadog:
  agent:
    host: localhost
    port: 8125

server:
  port: 8081

ports:
  outbound:
    http:
      connect-timeout: 5000
      read-timeout: 5000
      person:
        url: http://person-service:8080